[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-server"
version = "0.6.0"
requires-python = ">=3.11"
dependencies = ["fastapi", "uvicorn", "python-multipart", "core_specifications>=0.4.0", "agent_facade", "rag_facade", "data_facade", "auth_facade>=0.2.0", "observability"]
